### ISSUE TITLE
Insert in contenteditable block

### ISSUE THREAD

**Issue by wayheming** [karalamalar/insertAtCaret#5]
Hello, thank you for the library, I wanted to ask if it could be somehow modified so that it would be possible to use it for contenteditable blocks?

**Comment by emreerkan** [comment]
Hello @wayheming,

v1.2.0 now supports elements with `contenteditable="true"`. Could you please test and let me know if everything is allright. I'm closing this issue, fyi.

Cheers

**Comment by wayheming** [comment]
Hi @emreerkan, thanks for adding this feature, but I have some problem, I think we need to add "focus" at the beginning, because the text can be randomly added to the page where I clicked before

**Comment by emreerkan** [comment]
@wayheming you're right. I think I should write tests for this. I did all of the functional tests by hand and I missed this.

I released [1.2.1](https://github.com/emreerkan/insertAtCaret/releases/tag/1.2.1) for this. Thanks for reporting.

**Comment by wayheming** [comment]
Everything works, but the behavior at one moment is different from the usual input. For example, if you don't have focus and insert text, then in normal input it is always added at the end, but when you do the same in contenteditable, then it is always at the beginning. Steps to see:

1. Set focus to another element/input
2. Insert text by btn click

**Comment by emreerkan** [comment]
ContentEditable works that way. Put two ContentEditable elements, move caret to a position, then use <kbd>tab</kbd> to focus to the next element and use <kbd>shift</kbd>+<kbd>tab</kbd> to focus on the ContentEditable element again. You'll see that it'll reset the caret at the start.

**Comment by wayheming** [comment]
Yes, you are right, thanks for the explanation
